config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  devise_for :users
  resources :events
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  has_one_attached :image

  belongs_to :user

  validates :title, presence: true
  validates :explanation, presence: true, unless: :was_attached?
  validates :done_at, presence: true
  validates :people, presence: true
  validates :address, presence: true


  def was_attached?
    self.image.attached?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :events
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :profile])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def create
    Event.create(event_params)
  end

  def destroy
    event = Event.find(params[:id])
    event.destroy
  end

  def show
    @event = Event.find(params[:id])
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    event = Event.find(params[:id])
    event.update(event_params)
  end

  private

  def event_params
    params.require(:event).permit(:title, :image, :explanation, :done_at, :people, :address).merge(user_id: current_user.id)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/events/create.html.erb
<div class="contents row">
  <div class="container">
    <h3>イベントを企画しました！</h3>
    <%= link_to '投稿一覧へ', events_path, {class: "btn btn-info btn-block"} %>
  </div>
</div>

app/views/events/destroy.html.erb
<div class="contents row">
  <div class="container">
    <h3>イベントを削除しました！</h3>
    <%= link_to '投稿一覧へ', events_path, {class: "btn btn-info btn-block"} %>
  </div>
</div>

app/views/events/edit.html.erb
<div class="contents row"> <div class="container">
<h3>編集する</h3>
<%= form_with(model: @event, local: true) do |form| %>
  <div class="form-group">
        <%= form.text_field :title, placeholder: "Title" %>
      </div>
      <div class="form-group">
        <%= form.file_field :image, class: 'hidden' %>
      </div>
      <div class="form-group">
        <%= form.text_area :explanation, placeholder: "概要" %>
      </div>
      <div class="form-group">
        <%= form.datetime_select :done_at, placeholder: "開催日時" %>
      </div>
      <div class="form-group">
        <%= form.number_field :people, min: 0, placeholder: "人数" %>
      </div>
      <div class="form-group">
        <%= form.text_area :address, placeholder: "実施場所" %>
      </div>

      <%= form.submit "SEND", class: "btn btn-primary" %>
<% end %> </div>
</div>

app/views/events/index.html.erb
<div class="top-message-1">
  <h2 class="text-center">Let's create Events!</h2>
</div>
<div class="new-event">
  <%= link_to "New Post", new_event_path, class:"btn btn-outline-warning btn-block"%>
</div>

<div class="top-message-2">
  <h3 class="text-center">イベント一覧(新着順)</h3>
</div>
<div class="row">
  <% @events.each do |event| %>
    <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title"><%= event.title %></h5>
        <p class="card-text"><%= event.explanation %></p>
        <%= link_to "Event details", event_path(event.id), method: :get, class:"btn btn-primary"%>
      </div>
    </div>
  </div>
  <% end %>
</div>
</div>

app/views/events/new.html.erb
<div class="contents row">
  <div class="container">
    <h3>Create Event</h3>
    <div class="form-horizontal" role="form">
    <%= form_with(model: @event, local: true) do |form| %>
      <div class="form-group">
        <%= form.text_field :title, placeholder: "Title" %>
      </div>
      <div class="form-group">
        <%= form.file_field :image, class: 'hidden' %>
      </div>
      <div class="form-group">
        <%= form.text_area :explanation, placeholder: "概要" %>
      </div>
      <div class="form-group">
        <%= form.datetime_select :done_at, placeholder: "開催日時" %>
      </div>
      <div class="form-group">
        <%= form.number_field :people, min: 0, placeholder: "人数" %>
      </div>
      <div class="form-group">
        <%= form.text_area :address, placeholder: "実施場所" %>
      </div>

      <%= form.submit "SEND", class: "btn btn-primary" %>
    <% end %>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<div class="more">
      <ul class="more_list">
        <li>
          <%= link_to '編集する', edit_event_path(@event.id), method: :get, class:"btn btn-success" %>
        </li>
        <li>
          <%= link_to '削除する', event_path(@event.id), method: :delete, class:"btn btn-success" %>
        </li>
      </ul>
</div>



<div class="event-show">
  <div class="contents">
    <div class="event-title">
      <%= @event.title%>
    </div>
    
    <div class="event-image">
      <%= image_tag @event.image.variant(resize:'300x300') if @event.image.attached? %>
    </div>
    <div class="event-date">
      <p>開催日時</p>
      <%= @event.done_at %>
    </div>
    <div class="event-address">
      <p>開催場所</p>
      <%= @event.address %>
    </div>
  </div>
</div>

<div class="event-people-info">
  <div class="event-people">
    <p>現在の参加人数</p>
    <%#= イベント参加の人数 %>
  </div>
  <div class="event-people-all">
    <p>イベント参加者一覧</p>
    <%#=参加者一覧をeachで一覧表示する%>
  </div>
</div>

<div class="event-comments">
  <p>コメント</p>
</div>

app/views/events/update.html.erb
<div class="contents row"> <div class="success">
<h3>更新が完了しました。</h3>
<a class="btn" href="/">投稿一覧へ 戻る</a>
</div> </div>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eventer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_pack_tag 'application' %>
    <%= stylesheet_pack_tag 'application' %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="header">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/">Eventer</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            
            <% if user_signed_in? %>
              <li class="nav-item">
              <%= link_to 'Event Top', events_path, {class: "nav-link"} %>
            </li>
              <li class="nav-item">
                 <%= link_to "ログアウト", destroy_user_session_path, class: "nav-link", method: :delete %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to "ログイン", new_user_session_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "新規登録", new_user_registration_path, class: "nav-link" %>
              </li>
            <% end %>
          </ul>
          <% if user_signed_in? %>
          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
          <% end %>
        </div>
      </nav>
    </header>

    
    <%= yield %>
    <footer class="footer mt-auto py-3">
      
      <span class="text-muted">© 2020 Copyright:Eventer</span>

    </footer>
  </body>
</html>